### PR TITLE
fix:(comm) Socket Connection fixes

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/comm.py:
  Store the connection name to improve logging.
  Fix exception handling.

d_rats/ddt2.py:
  Fix exception handling.

d_rats/transport.py:
  Fix and exception handling.
  Improve logging.
  Implement automatic reconnection to broken connections.

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
With this code, on the usual windows 10 machine i use to perform test, if go to "edit preferences" and hit "save" d-rats get stuck (application not responding with all commands greyed out).

latest lines in console are:

```
03/19/2022 23:47:23:INFO:gps:set_units: Set GPS units to Metric
03/19/2022 23:47:23:INFO:MainApp:refresh comms
03/19/2022 23:47:23:INFO:MainApp:_refresh_comms: Stopping USA Philadelphia Digital Radio Association (PDRA) K3PDR
03/19/2022 23:47:23:INFO:Transporter:__worker: [NET k3pdr.dstargateway.org:9000-IZ2LXI] Waiting for reconnection...
03/19/2022 23:47:28:DEBUG:Transporter:__worker: [NET k3pdr.dstargateway.org:9000-IZ2LXI] Attempting reconnect...
03/19/2022 23:47:28:INFO:SocketDataPath:connection to k3pdr.dstargateway.org 9000
03/19/2022 23:47:29:INFO:SocketDataPath:getline: Host does not require authentication

```

**Comment by wb8tyw** [comment]
Reproduced the hang by opening config, going to the radio section and then clicking Save.
Will need to try to find out where this failure is happening, and it will probably need at least temporarily adding more logging.

**Comment by wb8tyw** [comment]
I probably going to be making mulitple updates to this PR, and that will probably result in having to having to do a squash/merge and edit of the commit message instead of a simple merge, so I will want to do that merge operation.

**Comment by wb8tyw** [comment]
I think this problem existed before, but was made much worse by my previous commit.

A broken connection and a shutdown condition were using the same flag.
We need an additional shutdown flag to indicate that the connection is being intentionally shutdown, and should drain.

Also fixed up the documentation and setup proper signaling on the RS-232 connection.

Need a followup ticket for use separate threads for sending and receiving operations to reduce the polling overhead and related problems.

**Pull request merged**
