### PR TITLE
Starting to plot points

### PR DESCRIPTION
**Pull request by wb8tyw**
Added the code to actually start plotting points.
Some of the menu items for acting on points are still not implemented.

d_rats/mainapp.py:
  Temporarily disable USGS and NBDC Map sources.

d_rats/map/mapdisplay.py:
  Add test of loading map overlays.

d_rats/map/mapdraw.py:
  Add draw_cross_marker_at method.
  Add draw_image_at method.
  Implement draw_marker method.
  Add draw_text_marker_at method.
  Add set_zoom_changed method.

d_rats/map/mapmarkerlist.py:
  Implement rendering the stored lists.
  Implement recenter callback method.
  Add a Unit test.

d_rats/map/maptile.py:
  Rename axis to tile in variable names
  Add some assistance with calculating the map fudge factor.

d_rats/map/mapwidget.py:
  Attempt to fix Map fudge calculations.
  Implement point_is_visible method.

d_rats/map/mapwindow.py:
  Add the add_map_source method.
  Add the del_point method.
  Add the maybe_recenter_on_updated_point method.
  Improve Docstrings

d_rats/map/mapzoomcontrols.py:
  Add call to MapDraw set_zoom_changed method.

d_rats/map_sources.py:
  Start python3 / Gtk3 Conversion.
  Convert to logging module.
  Add some temporary diagnostics,

d_rats/miscwidgets.py:
  Gtk 3 updates.
  Improve Docstrings.

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
Ciao,
i downloaded the code and did some tests.

unit test on mapdisplay:  python3 -m d_rats.map.mapdisplay.py 

produces this error:
/usr/bin/python3: Error while finding module specification for 'd_rats.map.mapdisplay.py' (ModuleNotFoundError: __path__ attribute not found on 'd_rats.map.mapdisplay' while trying to find 'd_rats.map.mapdisplay.py')

invoking: python3 ./drats.py 

it makes it run and display maps.

issues (which you are already aware) are:
- at zoom level 14 my location is correct, changing to greater level, it goes north of some centimetres
- if the map tiles from thunderforest are not cached it loads from web but displaying the  watermark "key not present" - you probably are not appending the key parameter from the config  file?
- if i go to preferences and change the map to be configured, this is not changed until i reopen the entire d-rats 

General issues
- after a while of inactivity d-rats disconnects from internet (this was a bug reported to me several times. but on my raspberry and windows was not appearing) although it seems still connected. -- the evidence which is disconnect is that if i try a ping all, it shows some lines in the prompt, but the messages remain stuck somewhere

- there is still a "d" prefix in the callsigns being diaplayed in messages shown in the bottom left of the d-rats main window

**Comment by wb8tyw** [comment]
I run this to run the unit tests.  No ".py" suffix.
```bash
python3 -m d_rats.map.mapdisplay
```

I will need to check my wiki to see if I accidentally added a .py suffix to the examples instead of pasting a working command.

I am still testing with the openstreet maps that are preconfigured in the d-rats defaults at the time that I created the branch.

As far as the offset, changing wtih the zoom, we may need to find someone better at understanding the map API or the translations from degrees to map than us.  I do not know how to come up with a universal "fudge" factor.   We may end up having to provide a way for people to adjust until their home marker is where they think it should be for each zoom level and then save that as a configuration for the map source.

It looks like for zoom 16, my correction factor is still off for the X axis for my house by a few mm.  The marker should be a few mm to the west than it is.

At zoom 15, the map have boxes for the houses for me.  At zoom 16, they do not.,  But at zoom 17 and 18 outlines for the houses and fences are shown.

I thought the fudge factor did not need correction below zoom 14.  It appears I am wrong as I see one other station close to mine that is getting farther from me as I lower the zoom level.  It should be getting closer to me.  So something is still wrong there.

I have not tested with the thunderforest maps.  I think that for that we have to have people obtain and install a their own key.   If we bundle in the thunderforest maps in the default configuration, they require a specific copyright message in the d-rats signon.

Right now I am just happy that I have markers that look close to where they should be.

On the other issues:

On my windows 7 laptop, it looks like it does disconnect from the Internet, but is not logging a disconnect.  I just stop seeing updates from the ratflectors.   Many ISPs will disconnect a TCP/IP connection for an idle condition.   The d-rats code is supposed to detect this as a socket error condition, and then reconnect.  I do not see that happening in the logs.

On an older version of d-rats on an older windows system, d-rats would make a core go 100% CPU bound when the ISP disconnected the session.

Note that even if your ISP does not do this disconnect, the ISP for the ratflector side may be doing this.  Not all ISPs will admit that they are doing this, but some will actually put the fine print of their user agreement.

So we need to figure out how do a keep-alive that does not end up going over the air.

The ping however should not just get stuck.  That is a different issue, one that I will see if I can find out independent of this set of map PRs.

Not seeing any 'd' or 'b' prefixes anywhere on callsigns, but have discovered that I can not hide the Stations panel.
I really had not been paying attention to those messages.

On a ping message, yes I see on the
```
Station XX#XXX is now online:" b`Online (D-RATS)'
```
The text quoted with b`xxxx` is how the data is actually sent over the air/internet and is passed to the event logger that way.   The additional b tick quoting is a feature of Python3.

Its purpose sometimes is diagnostic, and some of that data can not be translated to UTF-8 or other text encodings.  But we can select on a message by message basis if we want to display translated data or not by modifying the source.  The existing code is going to default to having some of the text be quoted that way in event messages and log messages.

One side effect of that is that some bytes in the log messages were non-printing and python2 just passed them through, so you could not see them in the log.  With python 3 those will be displayed, usually in an escaped notation.

Next I want to implement the rest of the Map menu items that are stubbed out and get see about getting the geopy dialog working when that package is installed.

**Comment by maurizioandreotti** [comment]
Hi John

quick one / bit of history on the thunderforest map: i added these (back in
2015...)  as at some point in the past, here in italy, the openstreetmap
were no more served with a useful level of zoom for our needs

i recall that some local map server resolved as openstreetmap.org was
denying access and these of thunderforest were the only one usable that i
found.

fixing the maps was the key point for me to put hands on drats (and - being
not a programmer - to scale up all the knowledge to understand how to make
the source run, modify and compile for linux and then win... a months of
trial and errors...,)

tracking radio positions it was a key application in our ham services with
icom radios in the alps for emergency interventions and support to "sky
races" competitions
see some photos of events here:
- https://www.arilecco.it/radio-emergenza/esercitazione-provinciale-2018/
-
https://www.arilecco.it/attivit%C3%A0-anni-precedenti/attivit%C3%A0-2015/giir-di-mont-2015/

all other improvement related to fixing /improving drats come later (always
with a trial and error approach) e.g. openweather, logging, and other
smaller things.

to come back to thunderforest, if you see the implementation in latest py2
d-rats, it  allows a number of different map urls which can be fully
configured with "base url" and then a postfix to be able to pass own key
for accessing the map server

I did this as the original d-rats app had the urls hard coded and there was
no flexibility to get other map tiles.

btw, the thunderforest key which you see in the config is just a sample of
how to compile the , as i am using "my own" thunderforest key, this is not
distributed as it is mine  (the one into the config is ="my key"+1 :-)

I am not sure about the disclaimer on "distributing the thunderforest" map.
i think it can be done, but maybe we could take it out and let users
configure it by themselves and have some nice user guide to configure it

I know that in some nations it can be used openstreetmap.de map server
without needing thunderforest


About the Fudge.... it was already there in the original code, and was
"roughly" working. I did some improvements adding some additional zoom
layers (as I was needing them) and applying some correction via trial/error.

The error in points placement increases at higher and lower levels of
zooms. the most part of it is on the vertical axis. I recall i was able to
correct it in acceptable way for zooms down to 18-19, and it was acceptable
from the higher zoom up to 4 or 5, then the plotting was quite randomic. I
found the error was not linear, but increasing going norther or
souther along the latitude. my guess is that is was related to the design
of the planisphere tiles of openstreetmap ... maybe due to some different
coordinates to be used e.g. wgs84 vs  mercator or anything

i did a number of tries, but not really got to a solution



Il giorno ven 28 gen 2022 alle ore 02:25 John E. Malmberg <
***@***.***> ha scritto:

**Comment by wb8tyw** [comment]
I think I have found the issue by looking at the source code.
Map tiles are obviously plotted correctly.
Points are not.

My development anti-x/linux laptop locked up while I was looking at the source to compose this, so I am using an alternate system while it reboots/updates, etc.
So I can not see the editor windows right now.  Anti-x is the only OS that I can find for both boots on it and almost properly supports using an external monitor on it.
I got it free, so there may be a hardware problem on it.   I can usually get a week of use out of it before having to reboot it.

Map tiles use deg2num which takes into account the curvature of the earth, and then truncates the point to match the tile position requested.

The points are plotted using latlon2xy, which is not taking into account either the zoom or the curvature of the earth.  Instead they are using a fudge factor.
I think this is why they are wrong.   The fudge factor will only ever be good for the specific center tile it was calculated for.

I think we need to have the points plotted by a variant of deg2num that returns a floating value.

**Comment by maurizioandreotti** [comment]
quick question:
where can i find the log file or how can i see the url that it's using for
getting the tiles? the new code dont print in the prompt any debug
message... there is some magic i am missing :-)

i tried adding a couple of lines in the mapdisplay (see from line 69 to 76)
and maptile to pass the apikey but it behaves the same and i was keen to
try this small mod... :-)

I checked in the usual places and I am not able to see any log file around.

thanks in advance
maurizio

Il giorno ven 28 gen 2022 alle ore 15:28 John E. Malmberg <
***@***.***> ha scritto:

**Comment by wb8tyw** [comment]
Add --loglevel DEBUG to the command that you run with.
I have been moving some of the messages to DEBUG level.

I have not tied the logging module into the windows event logger.  That is lower on my list.

**Comment by maurizioandreotti** [comment]
Thanks . For the time being I am just testin it with raspberry pi 2....

Il sab 29 gen 2022, 00:42 John E. Malmberg ***@***.***> ha
scritto:

**Comment by wb8tyw** [comment]
https://github.com/wb8tyw/D-Rats/wiki/MAP-Display-Part-2

Merging this in to work on the next set of fixes/changes.

**Comment by maurizioandreotti** [comment]
thanks

at quick check from logging,  when it tries to get thunderforest pngs it is
not appending the key,

as in the log and i see:
http://tile.thunderforest.com/landscape/10/542/367.png

and I would expect something like:
http://tile.thunderforest.com/landscape/10/542/367.png?apikey=5a1a4a79354244a38707d83969fd88a2

(note that this this key is "almost" valid, just substitute 2 at right with
1 to get to mine, in case you want to test it)

I also noted an additional issue, maybe already present in the pyhton2
code, in the maps storage folder i found folder:
- outdoor
White from the logging was expecting to store in:
- outdoors

so one of the two shall be a typo somewhere




Il giorno sab 29 gen 2022 alle ore 08:05 Maurizio Andreotti <
***@***.***> ha scritto:

**Pull request merged**
