### PR TITLE
fix(option): Fix config option

### PR DESCRIPTION
**Pull request by wb8tyw**
Fix setting the config directory option

d-rats.py:
d-rats_repeater.py:
  Use new platform set_base_dir method.
  Code Cleanup to be closer to current Python conventions.

d_rats/dplatform.py:
  Add set_base_dir method to allow changing the base directory.
  Remove python2 compatibility code.

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
Launching it with -c still doesnt work, this time blocks and exit in console:

$ python3 ./d-rats.py --loglevel DEBUG -c C:/Users/mauri/AppData/Roaming/D-RATS-test
06/27/2022 12:59:02:INFO:D-Rats:main: re-config option found -- Reconfigure D-rats
06/27/2022 12:59:02:INFO:D-Rats:main: args.config = C:/Users/mauri/AppData/Roaming/D-RATS-test
06/27/2022 12:59:02:INFO:Mainapp:Enabled debug log for Win32 systems
06/27/2022 12:59:03:DEBUG:Version:HTTP_CLIENT_HEADERS={'User-Agent': 'd-rats/0.4.00 pre-release1'}
06/27/2022 12:59:03:INFO:QST:FeedParser not available
06/27/2022 12:59:03:INFO:DratsConfig:File C:/Users/mauri/AppData/Roaming/D-RATS-test/d-rats.config
06/27/2022 12:59:03:INFO:DratsConfig:C:/Users/mauri/Desktop/D-RATS Shared
06/27/2022 12:59:03:INFO:DratsConfig:Creating directory for downloads: C:/Users/mauri/Desktop/D-RATS Shared
06/27/2022 12:59:03:INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "C:\msys64\home\mauri\D-Rats-wb8tyw_option\d-rats.py", line 93, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",



mauri@T450-Maurizio MINGW64 ~/D-Rats-wb8tyw_option

**Comment by wb8tyw** [comment]
It looks like for some unknown reason, some of the standard directories that Microsoft Windows creates are not present or have the wrong owner on your system, based on this and previous Windows tickets you have filed.

Was your home directory restored from another computer onto this one?
If so, all the directories in the restored directory may have the wrong owner.

My system with the patch installed has no problems creating and populating the directory no matter what syntax options that I use.

```text
$ python3 d-rats.py -c C:\Users\malmberg\AppData\Roaming\D-RATS-test
06/27/2022 08:10:37:INFO:D-Rats:main: re-config option found -- Reconfigure D-rats
06/27/2022 08:10:37:INFO:D-Rats:main: args.config = C:UsersmalmbergAppDataRoamingD-RATS-test
06/27/2022 08:10:37:INFO:Mainapp:Enabled debug log for Win32 systems
06/27/2022 08:10:38:INFO:QST:FeedParser not available
06/27/2022 08:10:39:INFO:DratsConfig:File C:UsersmalmbergAppDataRoamingD-RATS-test/d-rats.config
06/27/2022 08:10:39:INFO:DratsConfig:C:/Users/malmberg/Desktop/D-RATS Shared
06/27/2022 08:10:39:INFO:MainApp:_refresh_lang: Loading locale `en'
06/27/2022 08:10:39:INFO:MainApp:_refresh_lang: Locale dir is: //aviary/home/work/d-rats/D-Rats/locale
06/27/2022 08:10:39:INFO:MainApp:D-RATS v0.4.00 pre-release1 starting at Mon Jun 27 08:10:39 2022 on Platform Win32Platform:
  base:       C:UsersmalmbergAppDataRoamingD-RATS-test
  source_dir: //aviary/home/work/d-rats/D-Rats
```

OS Information:

```text
malmberg@CYBERDOG MINGW64 /w/work/D-Rats/D-Rats
$ python3 --version
Python 3.10.5

malmberg@CYBERDOG MINGW64 /w/work/D-Rats/D-Rats
$ cat /etc/os-release
NAME=MSYS2
ID=msys2
PRETTY_NAME="MSYS2"
ID_LIKE="cygwin arch"
HOME_URL="https://www.msys2.org"
BUG_REPORT_URL="https://github.com/msys2/MSYS2-packages/issues"
```

**Comment by maurizioandreotti** [comment]
I think can be merged.
_____________________
some more info and tests:

this PC was a clean install, and there is no other user in the system

both
```
    C:\Users\mauri\AppData\Roaming\D-RATS-EV
    C:\Users\mauri\AppData\Roaming\D-RATS-Test 

```appear to be owned by me and have similar permissions. 

Months ago the config file and all the rest into (C:\Users\mauri\AppData\Roaming\D-RATS-EV) was initially created using D-Rata 0.3.9 outside of msys. 

Now to perform this test i created a new empty folder
`C:\Users\mauri\AppData\Roaming\D-RATS-Test - 
`
and run drats from msys in this way: 
`~/D-Rats-wb8tyw_option$ python3 ./d-rats.py --loglevel DEBUG -c C:/Users/mauri/AppData/Roaming/D-RATS-tes
`
if i there is no config file into the folder , i get this error:
```
Traceback (most recent call last):

  File "C:\msys64\home\mauri\D-Rats-wb8tyw_option\d-rats.py", line 237, in <module>
    main()

  File "C:\msys64\home\mauri\D-Rats-wb8tyw_option\d-rats.py", line 217, in main
    app = mainapp.MainApp(safe=args.safe)

  File "C:/msys64\home\mauri\D-Rats-wb8tyw_option/d_rats/mainapp.py", line 365, in __init__
    self.config = config.DratsConfig(self)

  File "C:/msys64\home\mauri\D-Rats-wb8tyw_option/d_rats/config.py", line 2643, in __init__
    os.mkdir(default_dir)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/mauri/Desktop/D-RATS Shared'

```
If i put back a copy  of the config file in the folder, it was able to start and to modify it (and also to create all other folders for emails, logs debug file. etc:
`
mauri@T450-Maurizio MINGW64 /c/Users/mauri/AppData/Roaming/D-RATS-test
$ ls -la
total 33
drwxr-xr-x 1 mauri mauri    0 Jun 29 15:51 .
drwxr-xr-x 1 mauri mauri    0 Jun 25 19:18 ..
drwxr-xr-x 1 mauri mauri    0 Jun 27 13:04 Form_Templates
-rw-r--r-- 1 mauri mauri 9487 Jun 29 15:44 d-rats.config-x
-rw-r--r-- 1 mauri mauri 1003 Jun 29 15:47 debug.log
-rw-r--r-- 1 mauri mauri  340 Jun 29 15:51 list.txt
drwxr-xr-x 1 mauri mauri    0 Jun 27 13:04 logs
drwxr-xr-x 1 mauri mauri    0 Jun 27 13:04 messages
drwxr-xr-x 1 mauri mauri    0 Jun 27 13:04 static_locations
`

**Comment by wb8tyw** [comment]
@maurizioandreotti:

Your pasted outputs are showing two completely different paths for the directory.
In the failure case it is 'C:/Users/mauri/Desktop/D-RATS Shared'.
In the success case it is ''/c/Users/mauri/AppData/Roaming/D-RATS-test'.

On Windows 7, it appears that C:/Users/mauri/Desktop and /c/Users/mauri/AppData/Roaming are somehow linked to the same directory.

On Windows 10, possibly something different is going on with those two directories.  Where I am sitting right now, I do not have access to a Windows 10 system to experiment.

The failure was in creating the directory "$USERPROFILE/Desktop/D-RATS Shared" from python.

When a config file does not yet exist, the above path is used by d-rats as the download_dir directory and is attempted to be created.

If you have an existing config file, then that config file will specify what directory to use instead of "$USERPROFILE/Desktop" for your download directory.

That is probably an existing bug in d-rats to start creating folders and setting up the 'download_dir' before a user has confirmed that what directory they want use for a directory and that the directory actually exists.

But that is also a separate issue from this PR.

**Pull request merged**
