### PR TITLE
fix(GLib): GOobject.idle_add deprecated

### PR DESCRIPTION
**Pull request by wb8tyw**
d_rats/mainapp.py:
d_rats/map_sources.py:
d_rats/msgrouting.py:
d_rats/qst.py:
d_rats/session_coordinator.py:
d_rats/sessions/chat.py:
d_rats/sessions/rpc.py:
d_rats/ui/main_chat.py:
d_rats/ui/main_events.py:
d_rats/ui/main_files.py:
d_rats/ui/main_messages.py:
d_rats/wl2k.py:
  Use GLib.idle_add instead.

### CODE REVIEW

**Comment by wb8tyw** [comment]
This gets rid of a GObject.idlle_add is deprecated diagnostic that sometimes shows up, except the the emailgw module, which will be in a separate pull request.

**Comment by ka5mye** [comment]
John:

I did the clone and git checkout python3_tyw so that I had a fresh local
version after your email about fix #147.  

I ran before I had made the executable lzhuf in lib exec.  So I got an screen line
about lzhuf not found, of course.  But I noticed that the messages in the Outbox
were not routinely being locked as they had been.  Then I made lzhuf and reran.
The screen output shows lzhuf being run on one message with success. But there
was an exception:

04/09/2022 08:03:06:INFO:run_lzhuf:LZHUF returned 0
04/09/2022 08:03:06:INFO:wl2k_auto_thread:WL2K Mode is: Network
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/Users/rww/opt/anaconda3/envs/radio/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()

that I have not looked at yet.  But then the one message that lzhuf would be run on
was now being routinely locked.  A new piece of information about having the lzhuf 
executable built or not and the locking of files.

Thanks for the work on all of this and 73,

Rod



-------------------------------
Rodney Whitaker
KA5MYE
***@***.***

**Comment by wb8tyw** [comment]
Locking issues are currently collected in https://github.com/wb8tyw/D-Rats/issues/80

We need at least the lines of d-rats code in the error message trace back.

**Comment by ka5mye** [comment]
John:

 Thanks for letting me know. That was a little before I was getting involved and
I did not catch it.  

73,
Rod
 
 
-------------------------------
Rodney Whitaker
***@***.***

**Pull request merged**
