### PR TITLE
fix(version): One truth for version

### PR DESCRIPTION
**Pull request by wb8tyw**
Change the version to attempt to reflect the most current git tag.
This will provide more accurate versions for reporting issues.

PKG-INFO:
  Fix up the version information for legacy install.
  This file will be removed when the packaging code is updated.

d-rats.py:
d-rats_repeater.py:
  Fix shebang to work

d_rats/__init__.py:
  Fix comment

d_rats/version.py:
  Create a version class to lookup version from either git or
  the PKG-INFO file.

images/broken_tile.png:
  Make permission consistent

### CODE REVIEW

**Comment by wb8tyw** [comment]
This change makes the Git Tag what determines the Python version, which means that for running from a git checkout, it now displays an older base version.  It also displays the number of patches that have been added to the older base version.

**Comment by wb8tyw** [comment]
Minor fixup, remove a test print, and fix the detection of older beta tags.

**Comment by maurizioandreotti** [comment]
Good idea.



Il sab 23 lug 2022, 16:55 John E. Malmberg ***@***.***> ha
scritto:

**Comment by wb8tyw** [comment]
Unfortunately the PKG-INFO is not installed with the newer python packaging, even though it is generated.   Its replacement file named "METADATA" is also not in a location that is easy to look up.
It is looking like I may need to put something in a file named ${prefix}/share/doc/d-rats/versions and have d-rats find it on startup.  Alternate location is ${prefix}/share/d-rats

It also looks like d-rats does not know how to run from arbitrary ${prefix} and refuses to run from
being installed in a venv.   I am going to see if I can find a solution to those problems before I merge this patch.

**Comment by wb8tyw** [comment]
Looks like the best option is to have the build procedure create a setup_version.py file that will not be in the git repository.

Also fix up some parsing issues.

**Pull request merged**
